### ISSUE TITLE
Change Tampermonkey

### ISSUE THREAD

**Issue by vpswede98** [MeblIkea/NordicPlace#4]
Hey, 
I believe we should change the link in Read.me to https://www.tampermonkey.net/ instead of the current link: https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo 
This is to help people that use different browsers like Edge, firefox, safari and Opera to get started.

**Comment by ActuallyJustAVirus** [comment]
Did it thanks
